package org.yeastrc.ms.service.database.fasta;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.yeastrc.ms.domain.general.EnzymeRule;
import org.yeastrc.ms.domain.general.MsEnzyme;
import org.yeastrc.ms.domain.nrseq.NrDbProtein;
import org.yeastrc.ms.service.PeptideProteinMatch;

import junit.framework.TestCase;

public class PeptideProteinMatchingServiceTest extends TestCase {

    protected void setUp() throws Exception {
        super.setUp();
    }

    protected void tearDown() throws Exception {
        super.tearDown();
    }

    public final void testGetPeptideProteinMatch() throws SQLException {
        
        String proteinSequence = "MLPSWKAFKAHNILRILTRFQSTKIPDAVIGIDLGTTNSAVAIMEGKVPRIIENAEGSRTTPSVVAFTKDGERLVGEPAKRQSVINSENTLFATKRLIGRRFEDAEVQRDINQVPFKIVKHSNGDAWVEARNRTYSPAQIGGFILNKMKETAEAYLAKSVKNAVVTVPAYFNDAQRQATKDAGQIIGLNVLRVVNEPTAAALAYGLDKSEPKVIAVFDLGGGTFDISILDIDNGIFEVKSTNGDTHLGGEDFDIYLLQEIISHFKKETGIDLSNDRMAVQRIREAAEKAKIELSSTLSTEINLPFITADAAGPKHIRMPFSRVQLENITAPLIDRTVDPVKKALKDARITASDISDVLLVGGMSRMPKVADTVKKLFGKDASKAVNPDEAVALGAAIQAAVLSGEVTDVLLLDVTPLSLGIETLGGVFTKLIPRNSTIPNKKSQIFSTAASGQTSVEVKVFQGERELVKDNKLIGNFTLAGIPPAPKGTPQIEVTFDIDANGIINVSAKDLASHKDSSITVAGASGLSDTEIDRMVNEAERYKNQDRARRNAIETANKADQLANDTENSIKEFEGKLDKTDSQRLKDQISSLRELVSRSQAGDEVNDDDVGTKIDNLRTSSMKLFEQLYKNSDNPETKNGRENK";
//        String proteinSequence = "WFPCWGIYHQCLNEVSTAQQILKDVQEPVDLDNFRRIDNGTLKDTIRKLVLMARANRIANKHENEVRQVEEETIAGNSLLENANMVPLQIGTEEEIKKTPLDFGWNILPDFAFAELIAMLSGKNDRLVKMVNECTIRFSGEIGSVEMAYTLMRTLRFPVKEPFKERLIAAEFCDGFDIHIVKGTIRDLMLNSPHRDGLGLIYGTMSMVALSRTYTTRRELWTESSRSKLWLVKYLDQGETNNLAYTFVEVKQLLTLNDYDPAMQLMVWHEINLPIKKAERHERILVHFTDSNPVWGLLGSKPSLPIAPYQQIDLHRRFCEADNQLLTNVLGFLQMVLSDQRIDEHGKLVYKYDKGDSGKICFKRPRQKSSIVSFVPEFKSIKVIPKGGSARTGPVALELDHASLLKPSVHQLELTQLQPLQKGIKRFVNYYIDWAQNLNSVDKSKKYNMLWEYADNLDRGFSNQFSIERLTEPGRKLMEYLPELAAFMKETNHEGFFQRSADDLGEYWQEHWLVAMRILEHSVLEAQDVLVPSHIRMKEIISLAAKQRSLSESKIAVMLPYVLAQPHAKGLDSLLSLLSRSVIQNPQHIRSILQPLVELWTGIQILNFGEHMAQTAEPIGGFTFWLTLLRLADQLSSSESLSISHFFGKIAPIVHRHILNSSYHVEKADFTNVGIMGNDFENIDTVSSADSGEQKKKSVSTLMSIVEFNALAWNHWAKYWTNDFHTALLYSGLISDPNSLRWKPQLCVRWEGQKLFCRALLKTYDEVHRPVRKSQQPVSQAIMNNPDLGLDHAMRSTFNILQKLAEDQLGTAWLYKLQAYVVPPSAKATNPHDPDDTEELLTNLVKKALAMRGSKRCLNAFKIRVQADEKPKIVLSRVRLIRQWVDINKQCGLLRTNWTERMTLRKDSNQPLKKYKIIEELEAIIQARVVVNYARNYSENVLASLETVLLDRANFIHVEAKKFNNRHLCLIADYFEKDPSQSKMVSTYQAIEDWQELGWAAGAALPAMAKKVEPKATGWKESALKSLEEWEGLAYLSRLKGMMVEVSDEGAAEKENYAALADEWRQLKEYWTEKLQLENHQQAHKLIGIASDTQHLQNNISILAEITSNKPEELFEVEKYHLAKAFAHCKQAYKGLTHIPIPLPKDDHEMFEVLNLLMQYIEPPNESSSLAKCLAQILDEQYSTQLEVWCSSFSANFLERALPYYVSVLSSCSRLCASPSEKLLQISLRRIWEQWDEKTKQQSCYWANKLINQNVPLKTVQMEDEYNKREPVENEKDFIINTPLCENNLLKNVLQDYVSHQIRNRLLAKNIVPVFVVFDTGLQLLLLSLTNMTAKTLERDGNNLIRVLAQVIRSSMESLNINKALRGLTIISIKKLSGASYETMRVVIPMILHSYDELNPGFTVLSKLIRIPVIRKNSQDNELIDLFFTLTEPVFRKFEGELAKSISEIVSIITIQLKIIPFFERIVGYIKEVHPRIHQKVISILSGLQQFYFDLQSPPCSRMVLIIGPIIQDLFSVCRLGLNQFIHMIAQIAATHHISLSPDNLIKMLNHIVVTPYYEDNSPSVGQMLLAIDISPANQEVSSKSNSTVEIERHKYPDLAGLIGILRVTGRRIHPNNETKLINILIGLLEPYDLLPGVVYGSSAALQGLTTLAADRKFSNSQDQFTNIILPMLEKLYRTMEKGGVVSLEGLVKLATSAVASSADQCKPLIVDLIPDIYPKAVEDSSNILTCLLTASEEKKKPMNSFKLQTLLELLTKRLSPVVYAPNVSSLRGIIKIAELQIGFIEDNLAMFLLRLNDPQALQPDFNSGLHQLIELRIEAVPDTIAIMLLKSLVESVSHLAHVSTQKCIDDKIFLDCSTLAALKRVSSDEHEIYSITILRVFETLSYQHHILQLMKFCQILIQADTIDDNSEGTKKMFSQNRSKRAKEISFQNNFDYQNSQIFKEGSLSISLLNLIRSNVTSELSPIKENLIMLTEQMHDSMPCNLMLNLLDKNLHKAFAPGLACALKGICYFLDKEFQKRVKFKTRLGERINDLILTMYPSISSGVEFAIDGISVLIFPKDSNNAANMDINKLYRLYHVMIRDLYKKTFIAPDFAALLPLIAYVERRIVDFKYEKYKMTSKYIDDYKDRLYPAKLSLLERFVLLTAHVSDNTNLSLGHTCGQFLRQFWQKGLAPDRDQIITLCKGLAVAADLRIILKADRLPVWINDLISNVYPYLLYPSNDALAKIILLAAHRRYELKSSSSNNDATLTLWDICTRVEFEVFDSTLTGGPVTLRGLTNAALRMVEIDSSPILVRLYNALRSTQNPLEETSLYFSILTDVALIGGIKESSTFGHILEFIKNNLSNSFRQFQEASVERALSTLTTSLENAGSAREQPVDSKLKDFILNLTSFTTDLESDVFSIKGIHGASGTIVRGSDNPGNHNSDTNSTTSMEDDHSHSKHTLKKRTRHKGEARQRLSLLNPPTTYKNIYKNM";
        int minEnzymaticTermini = 1;
        String peptide = "IIENAEGSRTTPS";
//        String peptide = "LLTNVLGFLQMVLSDQRIDEHG";
        MsEnzyme enzyme = new MsEnzyme() {
            @Override
            public int getId() {
                return 0;
            }
            @Override
            public String getCut() {
                return "KR";
            }
            @Override
            public String getDescription() {
                return null;
            }
            @Override
            public String getName() {
                return "Trypsin_K";
            }
            @Override
            public String getNocut() {
                return "P";
            }

            @Override
            public Sense getSense() {
                return Sense.CTERM;
            }};
        EnzymeRule rule = new EnzymeRule(enzyme);
        List<EnzymeRule> rules = new ArrayList<EnzymeRule>(1);
        rules.add(rule);
        
        NrDbProtein dbProt = new NrDbProtein();
        dbProt.setAccessionString("YEL030W");
        dbProt.setDatabaseId(178);
        dbProt.setProteinId(529942);
        
        PeptideProteinMatchingService service = new PeptideProteinMatchingService(178);
        PeptideProteinMatch match = service.getPeptideProteinMatch(dbProt, peptide, rules, minEnzymaticTermini, proteinSequence);
        
        assertNotNull(match);
        assertEquals(1, match.getNumEnzymaticTermini());
        
    }

}
